### ISSUE TITLE
Add design editor support

### ISSUE THREAD

**Issue by hennrunnel** [Voog/design-barcelona#43]

**Comment by SSirjes** [comment]
* [ ] Form - Background color: changing on page form bg-color it will change also comment form bg-color
Video: http://recordit.co/tghpnfMkph

**Comment by SSirjes** [comment]
* [ ] CONTENT background color don't apply to blog article page.
Video: http://recordit.co/OC04z5JfYi

**Comment by SSirjes** [comment]
* [ ] "Footer" - "Background color" don't work correctly in IE(11), Windows
1. Change footer background color, save
2. Go to preview mode. Saved background color is not displayed. It's displayed white in preview mode.
In other browser background color is covered.

**Comment by SSirjes** [comment]
* [ ] Blog tag differences in edit and preview mode
In edit mode tag text is visible, in preview mode tag text changes color

**Comment by SSirjes** [comment]
* [ ] **Article - tag names are not in dropdown menu visible**
![screen shot 2016-04-25 at 09 59 45](https://cloud.githubusercontent.com/assets/13623224/14776120/e6543486-0acc-11e6-8324-b62e6cef50eb.png)

**Comment by SSirjes** [comment]
III testing
* [ ] **Custom and form button hover diferences**
Video: http://recordit.co/GPkEldRbXx
