### ISSUE TITLE
Make blog article width dynamic depending on the total count of the articles.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-barcelona#75]
(Pull request: #79)

* With 1 article => 100%
* With 2 article => 50%
* With 3 article => 33.3%
* With 4 article => 25%
* With 5 article => 20%
* With 6 and more articles => Same way like now

**Comment by SSirjes** [comment]
* [ ] **Front page layout > after the third blog post can't add easily new post**
_Video: http://recordit.co/XEeqs3tsdp_
